version: '3.7'
services:

  mongodb:
    image: mongo:4.4
    hostname: mongodb
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data-mongodb:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: crumbl
      MONGO_INITDB_ROOT_PASSWORD: crumbl
      MONGO_INITDB_DATABASE: crumbl
  
  web:
    build: .
    restart: always
    hostname: hoster-api
    container_name: hoster-api
    depends_on: 
      - mongodb
    ports:
      - 8000:8000
    environment:
      HTTP_PORT: 8000
      MONGO_USERNAME: crumbl
      MONGO_PASSWORD: crumbl
      MONGO_DOMAIN: mongodb
      MONGO_PORT: 27017
      MONGO_DB: crumbl
      MONGO_COLLECTION: hoster

volumes:
  data-mongodb:
    driver: local
